client/front-end: Export orders as CSV.
decred/dcrdex pull request #1103
Opened 2021-06-08 21:26 UTC by martonp

This PR adds a button on the orders page that allows the user to download their orders in CSV format.

Closes #382

2021-06-08 21:27 UTC, martonp commented on client/webserver/site/src/js/orders.js
> -    const url = new URL(window.location)
I removed this since the updated query string is never used.

2021-06-08 21:32 UTC, martonp commented on client/webserver/site/src/js/orders.js
> +      const csvFile = new Blob([res.csv], { type: 'text/csv' })
A POST request was needed to be able to send a JSON object which could be deserialized as an OrderFilter. To trigger a download after a POST request, a fake link has to be created and clicked programatically. It's a bit hacky, but it seems to be the way most people do this.

2021-06-09 15:39 UTC, chappjc requested changes
Thanks for picking this up.

The download would be best as a .csv file download served from a handler on the web router (e.g. /orders/export) rather than CSV-in-JSON from an api endpoint.

In the previous incomplete work on this (https://github.com/decred/dcrdex/pull/877), URL query parameters with a GET were used instead of the fetch api with a POST. That previous way allowed the download link (an `a` tag, but I expect it could be a button too) to be clicked and the user provided with a download (i.e. `"Content-Disposition", "attachment; filename=orders.csv"` and `"Content-Type", "text/csv"`).

One thing that was unresolved with the previous shot at this, and which this PR would also need to change, is to convert the handler to do a streaming response instead of creating the entire csv in memory and then writing it.  Please have a look at how dcrdata presently does this with `csv.NewWriter(w http.ResponseWriter)`: https://github.com/decred/dcrdata/blob/ec6b0e6a4cf4f7bcc9b803ce41787197bfffa94e/cmd/dcrdata/api/apiroutes.go#L1619-L1622

We may end up having to go further than this by actually rigging the DB methods with streaming versions that feed each matching entry into a closure that encodes and writes, rather than returning all matching entries and then encoding and writing in the handler.  But let's move forward with just the streaming writes and the existing DB methods for now.

The draft in https://github.com/decred/dcrdex/pull/877 was not actually far off. Please review that solution and the reviews there from @buck54321 and myself.

2021-06-14 02:16 UTC, martonp commented
@chappjc Yeah definitely better to stream it down than to have it all in memory. I will close this PR and open a new one.

2021-06-14 02:16 UTC, closed without merging