Fix maxOrder when not enough balance
decred/dcrdex pull request #1126
Opened 2021-07-13 19:09 UTC by vctt94

This PR closes #1097.

It also adds a `Not enough funds` message when not having balance for the purchase.

![image](https://user-images.githubusercontent.com/15069783/125510791-cf66d4b7-937a-4d0f-977f-76032812c7f9.png)

2021-07-14 00:18 UTC, chappjc commented
Trivial conflict resolution for you.

2021-07-15 05:39 UTC, JoeGruffins commented
I was able to reproduce this when I learned that you need to have a high rate.

It is possible to have the message show if you so something like rate 1 -> 99999 -> 1
When you go back to one it keeps the message from 99999

![hasnotenuf](https://user-images.githubusercontent.com/34998433/125734543-82434e76-9a1e-4d0c-ac32-740f4ae3380f.png)

2021-07-23 15:17 UTC, chappjc requested changes
OK it works well now when I set my simnet's BTC balance to almost zero and try to get a max buy estimate.  No more `toString` error.

![image](https://user-images.githubusercontent.com/9373513/126803293-ee0cb745-99cb-454d-88ce-5d2f63603fbc.png)

But the "Not enough funds..." message runs into the "0 lots" test.  And with 0 lots now clearly shown, I'm not sure if the `maxNotEnough` span serves a purpose anymore.

Also I've seen the  "Not enough funds..." message hang around even after it's not applicable.  Let's remove it.

2021-07-24 13:44 UTC, vctt94 commented
Good catch @JoeGruffins haven't noticed it.

I removed the span.

2021-07-24 14:43 UTC, chappjc approved these changes
LGTM.  @JoeGruffins can reevaluate at his leisure now that the span is removed.

n2s: This needs to be cherry-picked for v0.2.1.

2021-07-27 18:26 UTC, buck54321 requested changes

2021-07-27 18:26 UTC, buck54321 commented on client/webserver/site/src/js/markets.js
> +    isSell ? this.preSell() : this.preBuy()
```javascript
if (this.isSell()) this.preSell()
else this.preBuy()
```
Same LOC, better semantics.

2021-07-31 14:36 UTC, merged