testing: loadbot and test webserver fixes
decred/dcrdex pull request #1173
Opened 2021-08-26 23:54 UTC by buck54321

2021-08-28 22:07 UTC, chappjc requested changes

2021-08-28 22:07 UTC, chappjc commented on dex/testing/loadbot/go.sum
> +cloud.google.com/go/bigquery v1.3.0/go.mod h1:PjpwJnslEMmckchkHFfq+HTD2DmtT67aNFKH1/VBDHE=
I was actually just going to test loadbot for some other work and I came across this go.sum issue, but also a build failure:

```
# decred.org/dcrdex/dex/testing/loadbot
./mantle.go:144:26: not enough arguments in call to c.InitializeClient
	have ([]byte)
	want ([]byte, []byte)
```

Would you roll the fix for this into this PR as well? `nil` for the restoration should be good I think?

2021-08-30 06:40 UTC, JoeGruffins approved these changes

2021-08-30 19:12 UTC, chappjc approved these changes

2021-08-30 19:13 UTC, merged