Fix max order UI.
decred/dcrdex pull request #1178
Opened 2021-08-28 16:04 UTC by martonp

There were multiple issues with the max order UI. There would be a console
error saying the the maxLoaded function was null. This would happen if there
were two concurrent requests where the one that started first finished last.
Also, if a cached value was input while a another value was being fetched,
the cached result would be overridden by the value being fetched from the
client causing a mismatch between the rate in the input box and the result
on the screen.

2021-08-28 17:22 UTC, buck54321 requested changes
Righteous changes, but there's a bug for estimating the **max sell with an empty book** where the loading spinner is not removed.

![Screenshot from 2021-08-28 12-19-33](https://user-images.githubusercontent.com/6109680/131225787-a5c1b050-8c20-4a7f-9c8c-63ee8fdd5631.png)

Granted, this won't be encountered often in the wild.

2021-08-30 13:23 UTC, martonp commented
@buck54321 Should have been hiding the spinner after errors as well. It should be good now.

2021-08-30 19:26 UTC, chappjc approved these changes
Issue is resolved.

2021-08-31 07:45 UTC, JoeGruffins approved these changes

2021-08-31 15:30 UTC, buck54321 approved these changes

2021-08-31 15:31 UTC, merged