Pt br
decred/dcrdex pull request #1185
Opened 2021-09-01 15:10 UTC by vctt94

This branch adds pt-br into dex.

Depends on #1127

2021-09-06 22:54 UTC, chappjc commented on client/webserver/site/src/js/locales.js
> +  [ID_NEW_WALLET_PASS]: 'definir nova senha para carteira'
Missing the added `ID_LOT` and `ID_LOTS`.

2021-09-06 23:42 UTC, chappjc commented on client/webserver/locales/pt-br.go
> +	"Wallets":               "Carteiras",
Would you add a map entry for `Export Trades` please.

https://github.com/decred/dcrdex/blob/6e6cac4bf16f42ee6ad9e47721bb15263874f22d/client/webserver/site/src/html/orders.tmpl#L39

2021-09-09 11:23 UTC, buck54321 requested changes
While reviewing this, I found some missing translations and added them in #1200. I hope we can sneak that in first and add those translations here.

But this work looks good. This PR will be a good reference for the next translator. And it's super fun using DEX in Portugese.

2021-09-15 16:00 UTC, buck54321 approved these changes
Good to go. 

I did find a couple more stray strings that weren't being translated, if you wanted to pick them up here.

`'Waiting for confirmations...'` (& others in `updateRegistrationStatusView`)
`'none selected'`

2021-09-16 15:07 UTC, chappjc approved these changes
LGTM too.  @vctt94 just have a look at buck's final review when you get a chance to make some small tweaks.

2021-09-20 16:43 UTC, merged