client/asset/eth: token prefactor
decred/dcrdex pull request #1523
Opened 2022-03-16 22:45 UTC by buck54321

Preparing for tokens. Peeled off of #1399.

```
Moves contractor from nodeClient to ExchangeWallet. The changes the
ethFetcher API quite a bit, but is overall a simplification. To accomplish
this, I moved the nonceSendMtx to from nodeClient to ExchangeWallet too.
Nonce generation and signing is moved into nodeClient.txOpts to dedupe.

Use block headers instead of full blocks for tip monitoring.

Simplify fundingCoin and eliminate fundingCoinID.

Simplify tests using more consts and simpler structs.
```

2022-03-16 22:54 UTC, buck54321 commented
Leaving this in draft for a minute. At least one harness test is failing, and I need to square with previous comments on #1399.

2022-03-24 09:28 UTC, JoeGruffins reviewed
Simnet tests failing consistently at `TestRedeemGas` and `TestReplayAttack`.

Unrelated, but when rebuilding site I see `1 high severity vulnerability`:
```
npm install

added 685 packages, and audited 686 packages in 3s

104 packages are looking for funding
  run `npm fund` for details

1 high severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
```

Unable to place buy order with:
```
[ERR] WEB: error placing order: new order request with DEX server 127.0.0.1:17273 market dcr_eth failed: rpc error: error code 22: signature validation failed
```

2022-03-27 23:46 UTC, JoeGruffins commented
The npm vuln solved by #1545 probably

2022-03-30 14:18 UTC, buck54321 commented on client/asset/eth/nodeclient_harness_test.go
> +				test.name, dexeth.WeiToGwei(wantBal), dexeth.WeiToGwei(bal), float64(diff.Int64())/dexeth.GweiFactor)
You're right. I've reverted to the old behavior. Something changed when I stopped specifying a `maxFeeRate` to `(*nodeClient).txOpts`, and I'm not certain why. Will follow up.

2022-03-30 14:21 UTC, buck54321 commented on client/asset/eth/nodeclient.go
> +	}
I'm think it just means that the transaction succeeded without error.

2022-04-01 04:41 UTC, martonp approved these changes

2022-04-01 04:41 UTC, martonp commented on client/asset/eth/fundingcoin.go
> +const tokenFundingCoinIDSize = 36 // address (20) + amount (8) + amount (8) = 36
Why are there two amounts? Do you mean two addresses, one for the user and one for the token contract? Also, this isn't being used anywhere.

2022-04-01 04:41 UTC, martonp commented on client/asset/eth/nodeclient.go
> +	fmt.Println("--signData", data, n.creds.addr)
you left a debug print

2022-04-04 18:08 UTC, chappjc requested changes
Looks nice.

2022-04-04 18:08 UTC, chappjc commented on client/asset/eth/nodeclient.go
>  	if err := n.addSignerToOpts(txOpts); err != nil {
I see some calls to `addSignerToOpts` left behind in several spots, but it looks like the intention is to have `(*nodeClient).txOpts` be doing that in addition to `GetPoolNonce`.

2022-04-04 18:08 UTC, chappjc commented on client/asset/eth/nodeclient.go
> +func (n *nodeClient) checkTxStatus(ctx context.Context, tx *types.Transaction, txOpts *bind.TransactOpts) (*types.Receipt, error) {
Only used in the tests, but I assume it's used in the next steps of token work.

2022-04-04 18:08 UTC, chappjc commented on client/asset/eth/nodeclient.go
> +	if receipt.Status == 1 {
Let's use `core/types.ReceiptStatusSuccessful` instead of `1`.

2022-04-04 18:08 UTC, chappjc commented on client/asset/eth/nodeclient.go
> +	}
Yeah, looks to refer to the _execution_ of the transaction:

```go
const (
	// ReceiptStatusFailed is the status code of a transaction if execution failed.
	ReceiptStatusFailed = uint64(0)

	// ReceiptStatusSuccessful is the status code of a transaction if execution succeeded.
	ReceiptStatusSuccessful = uint64(1)
)
```

2022-04-04 18:08 UTC, chappjc commented on client/asset/eth/nodeclient.go
> +		return receipt, fmt.Errorf("gas used appears to have exceeded limit of %d", txOpts.GasLimit)
Might be helpful to include the value of `receipt.GasUsed` too.

2022-04-05 05:56 UTC, martonp commented on client/asset/eth/fundingcoin.go
> +const tokenFundingCoinIDSize = 36 // address (20) + amount (8) + amount (8) = 36
Ah makes sense, one is for the gas cost.

2022-04-06 20:14 UTC, chappjc approved these changes
LGTM.

@JoeGruffins Please circle back on your review when you get a chance.  Buck has addressed my concerns.

2022-04-08 14:17 UTC, merged