wiki: add get-started guide for Go fuzzing
decred/dcrdex pull request #1766
Opened 2022-08-08 16:24 UTC by ukane-philemon

This is a get-started guide that provides necessary information on how to start writing Go fuzz tests. I've tried to put all the necessary information in one place and added references to the Go docs. Part of #1748

2022-08-08 16:48 UTC, chappjc commented
Great start!  Thanks for the docs and the good first use case.

2022-08-17 21:22 UTC, chappjc requested changes

2022-08-17 21:22 UTC, chappjc commented on docs/wiki/Getting Started With Fuzzing.md
> +Go started supporting fuzzing in its standard toolchain beginning in Go 1.18. Fuzzing is a type of automated testing which continuously manipulates inputs to a program to find issues such as panics o
Let's link to https://go.dev/doc/fuzz/ in this paragraph.

2022-08-17 21:22 UTC, chappjc commented on dex/encrypt/encrypt_test.go
> +	})
Got a panic, negative slice length it seems:

```
=== FUZZ  FuzzDecrypt
fuzz: elapsed: 0s, gathering baseline coverage: 0/4 completed
fuzz: elapsed: 0s, gathering baseline coverage: 4/4 completed, now fuzzing with 32 workers
fuzz: minimizing 45-byte failing input file
fuzz: elapsed: 2s, minimizing
--- FAIL: FuzzDecrypt (1.99s)
    --- FAIL: FuzzDecrypt (0.05s)
        testing.go:1356: panic: runtime error: makeslice: len out of range
            goroutine 513 [running]:
            runtime/debug.Stack()
            	/home/jon/go119/src/runtime/debug/stack.go:24 +0xdb
            testing.tRunner.func1()
            	/home/jon/go119/src/testing/testing.go:1356 +0x1f2
            panic({0x62a620, 0x695060})
            	/home/jon/go119/src/runtime/panic.go:884 +0x212
            decred.org/dcrdex/dex/encode.RandomBytes(0xc000114220?)
            	/home/jon/github/decred/dcrdex/dex/encode/encode.go:65 +0x65
            decred.org/dcrdex/dex/encrypt.FuzzDecrypt.func1(0xc000382340, 0xffffffffffffffc3, {0xc000114220, 0x1, 0x10})
            	/home/jon/github/decred/dcrdex/dex/encrypt/encrypt_test.go:92 +0x167
            reflect.Value.call({0x626920?, 0x6629b8?, 0x13?}, {0x653599, 0x4}, {0xc00011a1e0, 0x3, 0x4?})
            	/home/jon/go119/src/reflect/value.go:584 +0x8c5
            reflect.Value.Call({0x626920?, 0x6629b8?, 0x51b?}, {0xc00011a1e0?, 0x761520?, 0x7838c0?})
            	/home/jon/go119/src/reflect/value.go:368 +0xbc
            testing.(*F).Fuzz.func1.1(0x1fbefaf4a4f5b574?)
            	/home/jon/go119/src/testing/fuzz.go:337 +0x231
            testing.tRunner(0xc000382340, 0xc0001f0090)
            	/home/jon/go119/src/testing/testing.go:1446 +0x10b
            created by testing.(*F).Fuzz.func1
            	/home/jon/go119/src/testing/fuzz.go:324 +0x5b9
            
    
    Failing input written to testdata/fuzz/FuzzDecrypt/465a95d340d5bc76fcb0352a6608e97a0ca215efcabd41010b86359b8f7d3cd1
    To re-run:
    go test -run=FuzzDecrypt/465a95d340d5bc76fcb0352a6608e97a0ca215efcabd41010b86359b8f7d3cd1
FAIL
exit status 1
FAIL	decred.org/dcrdex/dex/encrypt	2.272s
```

```
$  cat testdata/fuzz/FuzzDecrypt/465a95d340d5bc76fcb0352a6608e97a0ca215efcabd41010b86359b8f7d3cd1
go test fuzz v1
int(-61)
[]byte("0")
```

2022-08-17 21:22 UTC, chappjc commented on docs/wiki/Getting Started With Fuzzing.md
> +    **Note**: Fuzzing cannot be run for multiple packages at the same time using the `-fuzz` flag. You must specify at most one Fuzz test (e.g `-fuzz=FuzzXXX`) (See [suppport for multiple Fuzz tests]
From "To enable..." down to here is indented as part of the previous bullet.  Once you get markdownlint running and remove stray spaces it should start to look right.

2022-08-18 12:03 UTC, ukane-philemon commented on dex/encrypt/encrypt_test.go
> +		f.Add(rand.Intn(100), seed)
> I'm curious how the value of the integer and the length of the seed byte sliced affects the values the fuzzer feeds to the ff func.

The value of the integer and length of the seed does affect seeds generated by the fuzzer. It needs sensible seeds to replicate the same. But even if we at times get undesired seeds, we can always use a filter to skip seeds that are sure to fail(malformed/bad seeds).

2022-08-18 12:06 UTC, ukane-philemon commented on docs/wiki/Getting Started With Fuzzing.md
> +## Writing a Fuzz Test
> In fact, let's create a ".markdownlint.json" at the repo root:

Are there more rules we'd like to add?

2022-08-18 14:25 UTC, ukane-philemon commented on docs/wiki/Getting Started With Fuzzing.md
> +		}
> Does the fuzzer have bounds

No, it doesn't. 

> Is it related to the seeds?

`a`'s length is random. The fuzzing engine only needs to know the parameter type and will generate new or mutate provided seeds.

2022-08-18 15:34 UTC, chappjc commented
Hang on.  😊. Narrow the scope back up.  We can get to a global lint policy later.  Just fuzzing now please

2022-08-18 15:35 UTC, ukane-philemon commented
Fuzzed for 8min+,  31 `new interesting seeds generated.
<img width="580" alt="Screenshot 2022-08-18 at 3 57 47 PM" src="https://user-images.githubusercontent.com/57448127/185435504-96cdac70-053d-4bb0-bbff-1f70ee69a9e1.png">

2022-08-18 15:37 UTC, ukane-philemon commented
> And then fix anything it's still complaining about.
> Hang on. 😊. Narrow the scope back up. We can get to a global lint policy later. Just fuzzing now please

😅 `markdownlint` kept complaining.

2022-08-18 15:42 UTC, chappjc commented
> > And then fix anything it's still complaining about.
> 
> > Hang on. 😊. Narrow the scope back up. We can get to a global lint policy later. Just fuzzing now please
> 
> 😅 `markdownlint` kept complaining.
> 
> EDIT: Should the global lint fix come in a separate PR?

Totally.  We can really dig into that, CI and all, in a follow up PR.

I get it though, it's like whackamole

2022-08-18 16:20 UTC, chappjc commented on package.json
> +    "lint": "markdownlint docs/wiki/*.md && markdownlint docs/release-notes/*.md"
Eh, this doesn't seem right.  I don't think we should make an npm package just to run a linter, especially not at the root of the repo and named "dcrdex".

I guess I kinda implied we'd need some kind of CI solution, but I just run markdownlint one of two ways: (a) VSCode extension, or (b) system-wide install of markdownlint-cli.

Let's figure out enforcement of markdownlint policy later, and just use our tentative policy we've discussed for the fuzzing markdown.

2022-08-19 04:46 UTC, chappjc commented
Looks, good.  One more thing - let's add `**/testdata/fuzz` to .gitignore

2022-08-19 07:21 UTC, JoeGruffins approved these changes

2022-08-19 07:21 UTC, JoeGruffins commented on docs/wiki/Getting Started With Fuzzing.md
> +  ```
What do I do with file2fuzz?

2022-08-19 07:21 UTC, JoeGruffins commented on docs/wiki/Getting Started With Fuzzing.md
> +philemon@Philemons-MBP encrypt % go test -v ./... --fuzz=FuzzDecrypt --fuzztime=10x
Maybe better to take out the name here, just $ maybe?
```
$ go test -v --fuzz=FuzzDecrypt --fuzztime=10x
```

2022-08-19 12:14 UTC, ukane-philemon commented on docs/wiki/Getting Started With Fuzzing.md
> +- Keeping auto-generated seed corpus in $GOCACHE increases the efficiency of the fuzzing engine. The more seed corpus the better.
>  do not do f.Clean(f func())

No, best practices ain't hard rules. Besides, `f.Clean(f func())` is not tied to cleaning up seed corpus.

2022-08-19 12:15 UTC, ukane-philemon commented on docs/wiki/Getting Started With Fuzzing.md
> +  ```
```text
To convert provided seed corpus files to Go fuzzing corpus format use [file2fuzz]
```

2022-08-19 15:08 UTC, chappjc commented on docs/wiki/Getting Started With Fuzzing.md
> +  ```
TBH this still isn't clear to me.  I can see that file2fuzz takes some binary file as input and outputs to the "Go fuzzing corpus format".  But what kind of input fie?  Then where do you put the output and how do you use it?

2022-08-19 15:16 UTC, chappjc commented on docs/wiki/Getting Started With Fuzzing.md
> +  ```
`file2fuzz` sounds like an alternative to using a random string of your choice to go in the `[]byte`.  Basically it puts the contents of the file into a corpus like:

```
go test fuzz v1
[]byte("<contents of file>")
```

And then you... ? put that somewhere for the go fuzz test to find and use?

2022-08-19 15:22 UTC, merged

2022-08-19 16:25 UTC, ukane-philemon commented on docs/wiki/Getting Started With Fuzzing.md
> +  ```
> And then you... ? put that somewhere for the go fuzz test to find and use?

Yes, `file2fuzz` has an `-o` flag that provides a path to write output(seed corpus in Go fuzzing corpus format) files to.