bonds: UI updates and import/export
decred/dcrdex pull request #2200
Opened 2023-03-03 14:11 UTC by chappjc

2023-03-14 21:12 UTC, martonp reviewed
During registration, on the wallet funding screen, it allows you to only deposit the amount required for 1 bond, but then when it's time to post the bond, it will reject if there is not enough for the second bond. Either we should allow the user to not have to reserve enough for the second bond, or not go to the next page.

Another issue I found was when exporting the account. I exported, created a fresh dexc with the same seed, then imported. The imported server did not show up, but after I restarted the dexc, I could see it. Might be a pre-existing issue.

2023-03-14 21:24 UTC, chappjc commented
> The imported server did not show up, but after I restarted the dexc, I could see it. Might be a pre-existing issue.

Yeah, this is the annoying `initializeDEXconnections` call.  I'll look at avoiding the restart but I think it might need to stay this way for now.

2023-03-15 16:08 UTC, chappjc commented
> During registration, on the wallet funding screen, it allows you to only deposit the amount required for 1 bond, but then when it's time to post the bond, it will reject if there is not enough for the second bond. Either we should allow the user to not have to reserve enough for the second bond, or not go to the next page.

This was one of the things I was still considering.  You're absolutely right of course, with the current UI.  What I was pondering is a new user that might want to post a single bond *without* maintenance.  Seeing as we'll need to add a check box for that and probably handle other edges, I think we can put that idea on the back burner until 1.0 or maybe 0.6.1.  The normal user will have a maintained account. 

Will change the wallet wait form so it waits for the amount that it suggests, which accounts for the overlap with maintenance running.

2023-03-15 20:12 UTC, chappjc commented on client/webserver/locales/pl-pl.go
> -	"2 Fund the Registration Fee": "2: Wnieś opłatę rejestracyjną",
I couldn't see a way to tame gofmt here, not without leaving these incorrect translations.

2023-03-15 20:26 UTC, chappjc commented on client/webserver/locales/en-us.go
> +	"Skip Registration":              "No account (view-only mode)",
Would be nice if we had a "stale" flag like with the notifications because this one isn't bad still.

2023-03-15 20:59 UTC, chappjc commented
![image](https://user-images.githubusercontent.com/9373513/225440818-3f24670f-fd1f-40fb-b9f8-a6ffe2da74ea.png)

![image](https://user-images.githubusercontent.com/9373513/225440857-28d2986c-418e-47cb-a000-cefa00fd5021.png)

![image](https://user-images.githubusercontent.com/9373513/225440866-8a727ad5-54fa-4ae4-bdb2-b88100eb4a9e.png)

![image](https://user-images.githubusercontent.com/9373513/225440880-34c1de8f-f075-4a10-a369-04b21bd15816.png)

![image](https://user-images.githubusercontent.com/9373513/225440892-9f09784c-02b0-4e08-8d44-443ca7d63aa5.png)
(I missed the conf countdown).

![image](https://user-images.githubusercontent.com/9373513/225440939-876607ec-dda4-4a6a-a370-c20444d6587b.png)

2023-03-15 21:04 UTC, chappjc commented on client/webserver/locales/en-us.go
> +	"Skip Registration":              "No account (view-only mode)",
Removed some and flagged some others with comments if they were still accurate.

2023-03-16 15:25 UTC, chappjc commented
The need to restart after import should also be resolved @martonp but I've not tested that.  If the required changes somehow turn out to be much bigger we'll have to punt on this.

2023-03-16 19:52 UTC, martonp commented
The import basically works now, but if there was an active bond then it is not able to do a refund 

```
2023-03-16 15:47:05.836 [WRN] CORE: Bond output not found, possibly already spent or never mined! Marking refunded. Backup refund transaction: 
2023-03-16 15:47:05.836 [ERR] CORE: Failed to mark bond as refunded: bond bucket does not exist: 376aae28be249c5c0494b21433d5df1144085b50cf957a3a2cba850e72cba8ac
```
I think this will require a more extensive change.

2023-03-16 20:02 UTC, martonp commented
It's not a huge deal, but I think the text `You may deposit as much as you like` might make people think you can deposit just the 10 DCR. Maybe below the `Bond Amount: 10 DCR` there could also be `Minimum Deposit: 20.01` in the same size text.

2023-03-16 20:19 UTC, chappjc commented
> The import basically works now, but if there was an active bond then it is not able to do a refund
> 
> ```
> 2023-03-16 15:47:05.836 [WRN] CORE: Bond output not found, possibly already spent or never mined! Marking refunded. Backup refund transaction: 
> 2023-03-16 15:47:05.836 [ERR] CORE: Failed to mark bond as refunded: bond bucket does not exist: 376aae28be249c5c0494b21433d5df1144085b50cf957a3a2cba850e72cba8ac
> ```
> 
> I think this will require a more extensive change.

Was there really no refund tx in the log or did you remove it for brevity?  I don't see why it wouldn't be exported and imported given

```go
RefundTx   []byte `json:"refundTx"`
```

but it really needs to be.

2023-03-16 20:28 UTC, chappjc commented
Oh wait, I think the server may have reported an unknown bond there.  I guess I'll toy with this some more.

2023-03-16 21:23 UTC, chappjc commented
Ah I need to update the `async exportAccount () {` in dexsettings.ts.  The JSON that the browser downloads lacks bonds.

2023-03-17 16:15 UTC, chappjc commented
Yeesh, finally got bond import working.  General cases:

- Restore from same seed, discover account done, then import account used to import previous bonds.  The bond key index will derive the correct private key.  We need to update any placeholder live and unspent bonds when importing, otherwise append new unspent bonds that are likely expired and need refund.
- New seed used, registered fresh, then import account used to import previous bonds.  The bonds to not apply to the account, so we must block this.  Further, the bond key index will NOT derive the correct private key.  The user must manually broadcast the refund tx from the JSON file.
- New seed used, import the account with its bonds.  The bonds do apply to the account, but as with the previous case the bond key index will NOT derive the correct private key, so automatic refund must use the backup refund tx (in `rotateBonds`).  However, this pays to a the old wallet.  This is a messy case and should only be considered as a recovery aid.

In the last two points above, this is an unfortunate consequence of how we switched from storing the bond private key in the DB to storing the key index since that is only helpful if the app seed is unchanged.  Since the backup refund tx pays to the old wallet, this is suboptimal, but at least they can restore the wallet if they had the original seed.

2023-03-17 21:43 UTC, martonp approved these changes
LGTM, all the import cases work well. Could optionally export the bond private keys so they can be used when imported with a dexc that was initialized with another seed. It's probably a niche use case though so probably not worth the time.

2023-03-20 14:47 UTC, buck54321 requested changes
I sent the exact recommended amount, but the registration sequence did not progress. I had so send more.
![image](https://user-images.githubusercontent.com/6109680/226374558-fa63a6d4-8f9d-4e4d-8011-9cdaf9b9e99f.png)

2023-03-20 14:56 UTC, chappjc commented on client/core/account.go
> +			// dc.acct.{bonds,pendingBonds,expiredBonds}, using server config...
add or update.  Probably other error prone stuff.

2023-03-20 15:11 UTC, chappjc commented on client/webserver/site/src/js/forms.ts
> +    // limits yet, and there needs to be considerable explanation of why
"there needs to be considerable explanation" --> "there needs for considerable explanation"?

2023-03-20 15:21 UTC, buck54321 commented on client/webserver/site/src/js/forms.ts
> +    // limits yet, and there needs to be considerable explanation of why
Oh. Hmm. I don't know how I was reading this.

2023-03-20 15:22 UTC, buck54321 approved these changes

2023-03-20 15:35 UTC, merged