server: TestMalformedSwap fails occasionally
decred/dcrdex pull request #2229
Opened 2023-03-18 09:27 UTC by norwnd

Resolves https://github.com/decred/dcrdex/issues/2228.

The reason for this occasional failure (best I can tell) is server responding with an `error` to client **before** server is ready (has released corresponding atomic var) to accept next request attempt.

The simple, robust way to resolve it would be to respond with `error` to clients only **after** server is ready to handle those follow-up requests (there are quite a bit of those in tests, we could potentially just retry there but it is messy and unnecessary imo).

2023-03-18 09:29 UTC, norwnd commented on server/swap/swap.go
>  	stepInfo.match.mtx.Unlock()
This is just to clarify what "handleInit gating" mechanism actually is (it is mentioned couple of lines above),

I read through the code to verify that it indeed works, but could also add a unit-test to cover this scenario if you want.

2023-03-19 14:23 UTC, chappjc requested changes
Alright, but pls change the new log severity.  ERR level logging means something is going wrong with the server software.  WRN similarly means something to be concerned about.  Failing to send a message to a remote client is extremely common on account of dropped connections, so DBG or get rid of the log.  There's nothing important in the error.

I remember the `endSwapSearch` change and I think I even started with it all over the place like this.  I hate bending over backwards for unit tests, but this does seem like a server behavior that is more correct.

2023-03-19 14:23 UTC, chappjc commented on server/swap/swap.go
> +		log.Errorf("Couldn't send 'redemption' request to user %v (%s) for match %v", ack.user, makerTaker(ack.isMaker), matchID)
Not an error.  Users drop conn all the time.  Debugf

2023-03-24 05:52 UTC, JoeGruffins approved these changes
Makes sense. Testing with some other prs but looks fine to me.

2023-03-24 07:55 UTC, JoeGruffins commented
Testing this out I see a client error that may or may not be due to these changes. It has been a while since I tested on testnet so not sure, but from client:
```
2023-03-24 07:10:56.202 [INF] CORE: Notifying DEX 127.0.0.1:17273 of our btc swap redemption 8b780b5b5639d91d61ff099b706011b31924693b0539c4142785ddc1a31a5304:0 for match 3e299ed1550883f32918cf4a871c83bceeb93574523c6d89d3382c5fa71bd508
...
2023-03-24 07:11:03.753 [INF] CORE: Retiring inactive order aa49a549e4019ba04b5afee0475b3cc175755d4db5cb443afb3cef678f4f7a16 in status executed
2023-03-24 07:11:04.875 [ERR] CORE: Route 'redemption' request handler error (DEX 127.0.0.1:17273): redemption request received for unknown order: {"sig":"304402203a0b855865bf2a282c994f869d77b81437eb73df389b61b2a5b9c845967eee45022033b0e38b44c3459a447c711f90126baa54497532bbb6ffd672fbe037b9d57ec4","orderid":"aa49a549e4019ba04b5afee0475b3cc175755d4db5cb443afb3cef678f4f7a16","matchid":"3e299ed1550883f32918cf4a871c83bceeb93574523c6d89d3382c5fa71bd508","coinid":"7bc216be02ccb9147f411f0ff74ddb8fc1f629c37a7f193603db72437d918af800000000","secret":"863b2fd062dddbf7dae01ae2ce755a9647e8c44ac50f60e27d3d59fc4efe98c5","timestamp":1679641864874}
```
on server:
```
2023-03-24 16:10:59.238 [DBG] SWAP: processRedeem: valid redemption {txid = 8b780b5b5639d91d61ff099b706011b31924693b0539c4142785ddc1a31a5304, vin = 0} (btc) spending contract {txid = 50ce90f792e9b01f1cd4e9a0edc440c53eaa8a4035204eec3dbbb1cfc9823f5c, vout = 0} received at 2023-03-24 07:10:59.238 +0000 UTC from 1aa4aec190d355ead10b956fed232f8329a3234a2062e467b97e1b2727c291aa (maker) for match 3e299ed1550883f32918cf4a871c83bceeb93574523c6d89d3382c5fa71bd508, swapStatus TakerSwapCast => MakerRedeemed
2023-03-24 16:10:59.239 [DBG] AUTH: Match success for user 1aa4aec190d355ead10b956fed232f8329a3234a2062e467b97e1b2727c291aa: strikes -56, bond tier 0 => tier 1
2023-03-24 16:10:59.239 [DBG] AUTH: Recorded order aa49a549e4019ba04b5afee0475b3cc175755d4db5cb443afb3cef678f4f7a16 that has finished processing: user=1aa4aec190d355ead10b956fed232f8329a3234a2062e467b97e1b2727c291aa, time=1679641859239, target=<nil>
2023-03-24 16:10:59.240 [DBG] SWAP: processRedeem: sending 'redemption' request to counterparty 3f340890d4a6a34cca889f16e99af25d07042e8f1c87e3d1fff7a71fa6bef4dd (taker) for match 3e299ed1550883f32918cf4a871c83bceeb93574523c6d89d3382c5fa71bd508
2023-03-24 16:10:59.241 [DBG] SWAP: Received 'redemption' acknowledgement from user 3f340890d4a6a34cca889f16e99af25d07042e8f1c87e3d1fff7a71fa6bef4dd (taker) for match 3e299ed1550883f32918cf4a871c83bceeb93574523c6d89d3382c5fa71bd508 (MakerRedeemed)
2023-03-24 16:11:01.863 [DBG] SWAP: handleRedeem: 'redeem' received from 3f340890d4a6a34cca889f16e99af25d07042e8f1c87e3d1fff7a71fa6bef4dd for match 3e299ed1550883f32918cf4a871c83bceeb93574523c6d89d3382c5fa71bd508, order d19b5e075d48db8645c0e35058c4b3d74bb70424acdc5c3bbfa28465cb987035
2023-03-24 16:11:01.864 [DBG] SWAP: Allowing until 2023-03-24 07:13:01.864000588 +0000 UTC (1m59.999999338s) to locate redeem from taker (MakerRedeemed), match 3e299ed1550883f32918cf4a871c83bceeb93574523c6d89d3382c5fa71bd508, tx f88a917d4372db0336197f7ac329f6c18fdb4df70f1f417f14b9cc02be16c27b:0 (dcr)
2023-03-24 16:11:04.874 [DBG] SWAP: processRedeem: valid redemption {txid = f88a917d4372db0336197f7ac329f6c18fdb4df70f1f417f14b9cc02be16c27b, vin = 0} (dcr) spending contract {txid = 0f6ef3151c06a1c6b3f1f083d5da111746cfd3484507c7ff4ecfec42dbb477ac, vout = 0} received at 2023-03-24 07:11:04.874 +0000 UTC from 3f340890d4a6a34cca889f16e99af25d07042e8f1c87e3d1fff7a71fa6bef4dd (taker) for match 3e299ed1550883f32918cf4a871c83bceeb93574523c6d89d3382c5fa71bd508, swapStatus MakerRedeemed => MatchComplete
2023-03-24 16:11:04.875 [DBG] AUTH: Match success for user 3f340890d4a6a34cca889f16e99af25d07042e8f1c87e3d1fff7a71fa6bef4dd: strikes -35, bond tier 0 => tier 1
2023-03-24 16:11:04.875 [DBG] SWAP: processRedeem: sending 'redemption' request to counterparty 1aa4aec190d355ead10b956fed232f8329a3234a2062e467b97e1b2727c291aa (maker) for match 3e299ed1550883f32918cf4a871c83bceeb93574523c6d89d3382c5fa71bd508
....
2023-03-24 16:15:44.680 [TRC] SWAP: checkInactionBlockBased: asset 0, match 3e299ed1550883f32918cf4a871c83bceeb93574523c6d89d3382c5fa71bd508 (MatchComplete)
2023-03-24 16:15:55.694 [DBG] ASSET[eth]: Tip change from 8708703 to 8708704.
2023-03-24 16:15:57.694 [TRC] ASSET[eth][RPC]: Healthy connections: [ws://127.0.0.1:8546]
2023-03-24 16:15:58.684 [DBG] ASSET[dcr][RPC]: New block 00000005a37c4745e8467405a68f09d10c53678dd806d7b58dd27fc002b3cde5 (1106992)
2023-03-24 16:16:04.875 [INF] SWAP: Timeout waiting for 'redemption' request from user 1aa4aec190d355ead10b956fed232f8329a3234a2062e467b97e1b2727c291aa (maker) for match 3e299ed1550883f32918cf4a871c83bceeb93574523c6d89d3382c5fa71bd508
2023-03-24 16:16:06.694 [DBG] ASSET[eth]: Tip change from 8708704 to 8708705.
2023-03-24 16:16:09.686 [TRC] SWAP: checkInactionBlockBased: asset 42, match 3e299ed1550883f32918cf4a871c83bceeb93574523c6d89d3382c5fa71bd508 (MatchComplete)
2023-03-24 16:16:12.738 [TRC] SWAP: checkInactionEventBased: match 3e299ed1550883f32918cf4a871c83bceeb93574523c6d89d3382c5fa71bd508 (MatchComplete)
2023-03-24 16:16:12.738 [DBG] SWAP: Deleting completed match 3e299ed1550883f32918cf4a871c83bceeb93574523c6d89d3382c5fa71bd508
```

So redemption request sent after received and validated. I have not seen this before so likely due to these changes. Not sure though.

2023-03-24 09:03 UTC, norwnd commented
> Testing this out I see a client error that may or may not be due to these changes.

Interesting. Does this happen often ?

Based on my read of the logs you have, looks like Maker retired order **before** server could send his final "Taker redeemed" msg to Maker which should ideally  never happen. I don't see how this could be relevant to functionality in this PR, it seems [this timer](https://github.com/decred/dcrdex/blob/c3558efba8158f4418fcc49bf992925497eafcdf/client/core/core.go#L8380-8391) fired too early. But then it seems there is no way to easily avoid this (to sync this timer with that _"Taker redeemed" msg to Maker_ request) ? Maybe we shouldn't log it as `ERR` if we are Maker receiving this "Taker redeem" notification from server ?

2023-03-24 14:06 UTC, chappjc commented
Don't worry about the order being retired before receiving the courtesy (and generally not useful) redemption info for the counterparty/taker's final redeem tx.  There's a long history around these final relatively useless requests.  Server just didn't send them at all for a long time.  Recently [started again](https://github.com/decred/dcrdex/pull/1866), but client cannot just wait for that request since it may never come (older server or other party just didn't bother to redeem, not affecting maker at all). See also https://github.com/decred/dcrdex/pull/1866

Let's not make any special cases for it either.  I'll consider the current state of things w.r.t. this but let's move on and focus on the present issue.

2023-04-10 15:57 UTC, merged