ui: prevent negative amt on send form
decred/dcrdex pull request #2253
Opened 2023-03-25 08:41 UTC by norwnd

When transaction fee is comparable to amount left in user wallet we might get into negative territory calculating max send value.

[send-negative-amt-ui.webm](https://user-images.githubusercontent.com/112318969/227706401-7bdb39db-46ef-4b50-b8df-9366643f31be.webm)

2023-03-27 03:44 UTC, JoeGruffins approved these changes

2023-03-27 13:49 UTC, chappjc approved these changes

2023-03-27 19:29 UTC, buck54321 requested changes

2023-03-27 19:29 UTC, buck54321 commented on client/webserver/site/src/js/wallets.ts
> +          }
One line please.

2023-03-28 03:06 UTC, norwnd commented on client/webserver/site/src/js/wallets.ts
> +          }
Changed.

2023-03-28 03:39 UTC, merged