site: Notify users when connecting wallets fail
decred/dcrdex pull request #2288
Opened 2023-04-04 08:02 UTC by ukane-philemon

Closes # 2241

> @norwnd (#2241): As a sidenote, I'm not even sure why this connect button is there in the first place , wouldn't it be better to try re-connect wallet automatically every 30s or something ?

This part is not handled in this PR. @chappjc, what do you think?

2023-04-04 15:33 UTC, chappjc commented
Yeah, I don't want to replace the connect button with a background reconnect loop.

Regarding any error from connect, I'm pretty sure we're trying to show errors on the page or form near the UI element interaction that generated the error, not the notification menu.  https://github.com/decred/dcrdex/issues/1712#issuecomment-1198568703

2023-04-05 21:02 UTC, buck54321 commented
I'd prefer to show the message on the page rather than as a tooltip.

2023-04-05 22:27 UTC, chappjc commented
How about an error message "form" that opens up with the messgae, so we don't have to pre-allocate real estate for an possible error?

2023-04-05 23:10 UTC, buck54321 commented
> How about an error message "form" that opens up with the messgae, so we don't have to pre-allocate real estate for a possible error?

Pre-allocating page space is the simpler option. The "form" you mention, as I understand, is an interactive (probably modal) dialog that would explain the error and possibly provide guidance or options for resolution. I do agree that such an experience is desirable. I'm not sure that we should try that in this PR.

2023-04-05 23:15 UTC, chappjc commented
Yeah, just something you can close when done reading.  But didn't mean to suggest we try to provide resolutions or anything smarter that just showing the error.
It's fine too drop the error in div or something on the page.  It can be hidden so it doesn't eat space unless needed. I just didn't want to sacrifice layout quality

2023-04-06 06:46 UTC, ukane-philemon commented
> I just didn't want to sacrifice layout quality

Yup, these errors can be ugly and I don't quite get where in the page @buck54321 wants this kind of error message since the table where the connect btn is located already has a lot.

2023-04-06 10:46 UTC, buck54321 commented
> > I just didn't want to sacrifice layout quality
> 
> Yup, these errors can be ugly and I don't quite get where in the page @buck54321 wants this kind of error message since the table where the connect btn is located already has a lot.

Just to echo @chappjc above

> I'm pretty sure we're trying to show errors on the page or form near the UI element interaction that generated the error

I think it looks alright on the page.

https://github.com/buck54321/dcrdex/compare/d165f1f...buck54321:dcrdex:ukaine-connect-err-on-page

![image](https://user-images.githubusercontent.com/6109680/230354734-db1aa969-47b0-455d-a057-dbfafa56456e.png)

2023-04-06 10:52 UTC, ukane-philemon commented
> I think it looks alright on the page.

For long errors like the eth error in my PR comment, it will easily look very ugly IMO. But if you want to, we can dump everything below the button.

2023-04-06 13:54 UTC, chappjc commented
> If using a tooltip is not a good resolution to this, we can use a general error modal that can be closed by the user when they are done reading and digesting the error, showing the whole error on the page beside the connect btn does not look desirable IMO.

A tooltip is not, I think we agree.  Sure, give the modal a try quick.  We just don't want a major production over this.

2023-04-07 09:22 UTC, ukane-philemon commented
https://github.com/decred/dcrdex/pull/2288/commits/757c9bc16f63c10c9dc69784d3804b2edc7f1327 UI changes.

<img width="507" alt="Screenshot 2023-04-06 at 10 58 57 PM" src="https://user-images.githubusercontent.com/57448127/230582955-9ccd0ebc-cd21-4e0f-8b3d-801b2218f753.png">
<img width="469" alt="Screenshot 2023-04-06 at 10 57 43 PM" src="https://user-images.githubusercontent.com/57448127/230582988-35d80fa7-4dd3-4d1b-bb57-487ecd7fd41f.png">

2023-04-07 15:45 UTC, chappjc commented
Seems alright I guess.  The work "Message" in "Error Message" is not needed though.  It's more like "Connect Error".  I also figured we'd have an "x" at the top right like all the other forms instead of an "Ok" button.  BTW, it's "OK" not "Ok"

2023-04-07 15:46 UTC, chappjc commented
Anyway, you and @buck54321 work out where to put the error, but IMO it gets messy putting it right next to the button.  I think the dialog form that opens is a good compromise because you can't ignore it like tooltips and notifications, and it doesn't touch the page layout.

2023-04-07 15:50 UTC, ukane-philemon commented
> I also figured we'd have an "x" at the top right like all the other forms instead of an "Ok" button.

I think it's better they acknowledge that they have seen the error, the x at the top is usually for form dismissal but we can have that instead of the btn if that's better or keep both?

> It's more like "Connect Error"

I wanted to be more flexible instead of tying the modal to only `Connect Error`.

2023-04-07 15:52 UTC, chappjc commented
>  I think it's better they acknowledge that they have seen the error, the x at the top is usually for form dismissal but we can have that instead of the btn if that's better or keep both?

Whatever really.  The button just looks funny.  It's chunky and big, and requires a translation (!).

> I wanted to be more flexible instead of tying the modal to only `Connect Error`.

Of course, but the "Connect" part can be a variable inserted by the JS caller.  If that's not trivial for whaterver reason, just "Error" is preferable to "Error Message", which looks silly.

2023-04-07 16:52 UTC, ukane-philemon commented
Update the images above.

2023-04-07 18:00 UTC, buck54321 requested changes
Please consider https://github.com/buck54321/dcrdex/compare/1e50d26...buck54321:dcrdex:error-modal-in-forms

2023-04-07 18:10 UTC, ukane-philemon commented
> Please consider [buck54321/dcrdex@1e50d26...buck54321:dcrdex:error-modal-in-forms](https://github.com/buck54321/dcrdex/compare/1e50d26...buck54321:dcrdex:error-modal-in-forms)

I could have used the existing form structure we have(less code) but the modal is not a "form". Still, we can run with your suggestion, I understand you prefer less code in this case.

2023-04-07 20:10 UTC, buck54321 approved these changes

2023-04-07 20:12 UTC, buck54321 commented
> I could use the existing form structure we have(less code) but the modal is not a "form". Still, we can run with your suggestion, I understand you prefer less code in this case.

It's not about less code. The existing forms **are** modal, since they prevent page interaction until the form is submitted or dismissed. No reason to reinvent the wheel.

2023-04-07 20:13 UTC, merged

2023-04-07 20:15 UTC, chappjc commented
Also, this isn't the first form used this way.  The "Export Wallet" form is also purely informational:

![eth-export-key](https://user-images.githubusercontent.com/9373513/230673051-8b47aed5-07fb-47fd-a29b-9d5224db9ca7.png)
(don't bother with the key, it's simnet)

2023-04-07 20:21 UTC, ukane-philemon commented
Noted.