client/ui: simplify enable/disable wallet for token/parent wallets
decred/dcrdex pull request #2324
Opened 2023-04-26 01:53 UTC by ukane-philemon

Closes #2242.

2023-04-28 19:42 UTC, chappjc commented
I don't I agree that token wallets should not be able to be disabled.
You can create a token wallet some time after creating the ETH wallet, and disabling a token wallet was working just fine.  I don't think we should prohibit that.

The error here seemed really really clear to me:

https://user-images.githubusercontent.com/112318969/226815886-a178b280-5e11-42ff-9018-c74de45c8a84.png

2023-05-09 17:46 UTC, buck54321 requested changes
Looking good. A couple of nits.

2023-05-09 17:46 UTC, buck54321 commented on client/rpcserver/handlers.go
> +		token wallets that depend on the wallet will be disabled.`,
"parent wallet" is what we use in code, but may not me customary. How about something like "When disabling a chain's primary asset wallet, all token wallets for that chain will be disabled too."

2023-05-09 17:46 UTC, buck54321 commented on client/core/core.go
>  		}
Might not matter, but we should probably disconnect and disable the parent wallet last.

2023-05-09 17:46 UTC, buck54321 commented on client/webserver/locales/en-us.go
> +	"enable_wallet_message":       "This wallet will resume operation and might take some time to sync. This will also enable the parent wallet if this is a token wallet.",
"If this is a token wallet, the wallet for the chain's primary asset will also be enabled."

2023-05-10 14:26 UTC, buck54321 approved these changes

2023-05-10 14:27 UTC, merged