build: golangci-lint v1.53.1
decred/dcrdex pull request #2375
Opened 2023-06-02 23:58 UTC by dajohi

2023-06-03 08:03 UTC, ukane-philemon approved these changes

2023-06-05 15:19 UTC, buck54321 requested changes

2023-06-05 15:19 UTC, buck54321 commented on .golangci.yml
Can add

```YAML
output:
  format: github-actions,colored-line-number
```

and remove the cli flag.

2023-06-05 15:19 UTC, buck54321 commented on .golangci.yml
> +    - vetshadow
From what I can tell, **vetshadow** is enabled by default with **govet**. They don't even document it as a separate linter. Can remove?

---

#### For documentation, the new linters added in the pull request are...
bidichk: Checks for dangerous unicode character sequences
durationcheck: check for two durations multiplied together
exportloopref: checks for pointers to enclosing loop variables
grouper: An analyzer to analyze expression groups, e.g. const, var
nosprintfhostport: Checks for misuse of Sprintf to construct a host with port in a URL
reassign: Checks that package variables are not reassigned in another package
tparallel: detects inappropriate usage of t.Parallel() method in your Go test codes
typecheck: Like the front-end of a Go compiler, parses and type-checks Go code

2023-06-07 17:41 UTC, buck54321 approved these changes

2023-06-07 17:41 UTC, merged