spec: Update admin.mediawiki
decred/dcrdex pull request #2470
Opened 2023-08-09 08:55 UTC by ukane-philemon

This diff updates admin.mediawiki and fixes broken links in fundamentals and orders `.mediawiki` pages.

2023-08-14 22:01 UTC, buck54321 requested changes

2023-08-15 09:42 UTC, ukane-philemon commented on spec/admin.mediawiki
> +| epoch&nbsp;duration || [[fundamentals.mediawiki/#epoch-based-order-matching|Epoch-based Order Matching]] || milliseconds || 20,000
Broken links.

2023-08-18 09:16 UTC, JoeGruffins approved these changes

2023-08-28 16:51 UTC, buck54321 approved these changes

2023-08-28 16:52 UTC, merged