client/multi: Consider refunds in market making
decred/dcrdex pull request #2479
Opened 2023-08-16 13:50 UTC by martonp

The possibility of refunds was previously ignored in the market making balance handling code.

- `core.SingleLotFees` now returns refund fees in addition to swap and redeem. This is needed because ETH reserves refund fees when funding a swap, so the market maker `MaxSell`/`MaxBuy` implementations need to know about this.
- `asset.SingleLotSwapFees` is now `asset.SingleLotSwapRefundFees`
- `core.FeeBreakdown` now includes Refund fees.
- The market maker balance handling code can now handle revoked matches and refunds.

The Refund field of `core.FeeBreakdown` is not yet populated. This will be implemented in a future diff.

2023-08-16 13:51 UTC, martonp commented
This is actually just a ~200 line diff, the tests are quite long.

2023-08-21 23:18 UTC, buck54321 requested changes

2023-08-21 23:18 UTC, buck54321 commented on client/mm/mm.go
>  		}
Why are we only accounting for refund fees if `initialRefundFeesLocked == 0` ?

2023-08-22 12:40 UTC, martonp commented on client/mm/mm.go
> +			}
Nah same thing. I'll update.

2023-08-25 02:59 UTC, JoeGruffins commented on client/mm/mm.go
> +						{balanceModDecrease, orderInfo.order.QuoteID, balTypePendingRedeem, calc.BaseToQuote(match.Rate, match.Qty) - maxRedeemFees},
Nah, just a preference. No problem.

2023-08-26 09:13 UTC, martonp commented
I made some changes to this. There is no more `PendingRefund` section in the `botBalance` struct. Matches are assumed to be redeemed until they are actually refunded. The only time a match being revoked is taken into consideration is if a swap transaction has not yet been made.

2023-08-28 03:00 UTC, JoeGruffins approved these changes

2023-08-28 03:00 UTC, JoeGruffins commented on client/mm/mm.go
> +//   - When a match is settles, the balances are updated differently depending
```suggestion
//   - When a match settles, the balances are updated differently depending
```

2023-08-28 03:00 UTC, JoeGruffins commented on client/mm/mm.go
> +		m.log.Errorf("oid: %s, match %s is in confirmed state, but no refund or redeem", oid, matchID)
Critical even. Surely we never get here.

2023-08-28 22:14 UTC, buck54321 approved these changes

2023-08-28 22:14 UTC, buck54321 commented
Please follow up on @JoeGruffins nits in another PR.

2023-08-28 22:15 UTC, merged