core: Fix nil bookie panic in `core.Book(...)`
decred/dcrdex pull request #2642
Opened 2023-12-26 20:32 UTC by ukane-philemon

2023-12-31 10:30 UTC, martonp approved these changes

2024-01-02 08:20 UTC, JoeGruffins approved these changes

2024-01-06 12:40 UTC, buck54321 requested changes
This can be done in +3 lines https://github.com/decred/dcrdex/compare/master...buck54321:bookpanic

Same thing, right?

2024-01-06 14:28 UTC, ukane-philemon commented
Yh, but I wanted to get rid of the "long" block of `if` statement.

2024-01-06 14:30 UTC, buck54321 commented
> Yh, but I wanted to get rid of the "long" block of `if` statement.

No thank you.

2024-01-06 14:31 UTC, ukane-philemon commented
Okay, one moment.

2024-01-06 15:26 UTC, merged