[auth] PruneBonds refactor
decred/dcrdex pull request #2650
Opened 2024-01-01 00:04 UTC by romanornr

2024-01-01 08:12 UTC, JoeGruffins approved these changes

2024-01-12 14:33 UTC, buck54321 requested changes

2024-01-12 14:33 UTC, buck54321 commented on server/auth/auth.go
> +	pruned = make([]*db.Bond, 0, len(client.bonds))
We don't really need to pre-allocate `pruned`. It won't be used often, and when it is is will be a single bond pretty much every time.

2024-01-12 14:33 UTC, buck54321 commented on server/auth/auth.go
> +	activeCount := 0
I prefer `var n int`.

2024-01-12 14:33 UTC, buck54321 commented on server/auth/auth.go
> +			expiredBondsInfo = append(expiredBondsInfo, fmt.Sprintf("Expiring user %v bond %v (%s)", client.acct.ID, coinIDString(bond.AssetID, bond.CoinID), dex.BipIDSymbol(bond.AssetID)))
Let's undo this change and just log it here. This doesn't provide any obvious benefit and new allocations and a second loop.

2024-01-12 14:38 UTC, buck54321 reviewed
Reversing the lock time logic makes sense, but the other changes don't improve anything, as far as I can tell.

Are you [on Element](https://docs.decred.org/getting-started/joining-matrix-channe)? You can always chat with us in the `DEX Development` room if you're looking for something to work on,.

2024-03-22 21:33 UTC, closed without merging