multi: add pre-paid bonds
decred/dcrdex pull request #2730
Opened 2024-04-05 12:09 UTC by buck54321

This adds "pre-paid bonds", invite codes generated by the server that the client uses to generate a cost-free, time-limited fidelity bond.

Access the pre-paid bond dialog with the button at the bottom of the bond tier dialog.

<img src="https://github.com/decred/dcrdex/assets/6109680/683a66d1-dd9c-4d13-895e-ce066ef24438" width="561">

Closes #2728

2024-04-05 14:53 UTC, exitus1 commented
If I'm reading this correctly, it's saying the bonds would be free?

2024-04-05 15:04 UTC, buck54321 commented
> If I'm reading this correctly, it's saying the bonds would be free?

Yes.

2024-04-11 06:23 UTC, JoeGruffins commented
Unable to redeem:
![image](https://github.com/decred/dcrdex/assets/34998433/3f34d788-6a78-4098-b85d-199c1f6dc9e3)

2024-04-11 06:34 UTC, JoeGruffins commented
When I click on "Change Tier" in settings after inputting a paid bond, it takes me to the redeem paid bond screen but it should be one screen before that to choose asset and tier.

2024-04-12 01:31 UTC, buck54321 commented
@JoeGruffins I squashed everything by accident, but I think I addressed your comments.

2024-04-12 05:38 UTC, JoeGruffins commented
Still seeing the problem:

https://github.com/decred/dcrdex/assets/34998433/43cb3665-e05c-4629-b487-1f76d57c223f

2024-04-13 16:20 UTC, buck54321 commented
> Still seeing the problem:
> 
>  stillnopass.mp4

Whoops. Should be fixed now.

2024-04-15 03:57 UTC, JoeGruffins commented
The previous problem looks fine.

But for some reason unable to trade.

I Made a simnet server with btc, dcr, and eth. I got some free bonds with `$ curl -k -u :adminpass "https://127.0.0.1:16542/api/prepaybonds?days=10&n=10&strength=5"`

I used one to make a new account, the server looks fine and says:
```
2024-04-15 12:50:41.451 [INF] AUTH: Creating new user account bc05c19c4f82ba9dec007dff529ad689ca91f29b981c69d3317310348f62e589 from pre-paid bond. addr = 127.0.0.1
2024-04-15 12:50:41.460 [INF] AUTH: Pre-paid bond accepted: acct bc05c19c4f82ba9dec007dff529ad689ca91f29b981c69d3317310348f62e589 from 127.0.0.1. Bonded tier 5, effective tier 5
```

But trying to trade I will see:
```
2024-04-15 03:53:52.679 [ERR] CORE: notify: |ERROR| (order) In-Flight Order Error - In-Flight order with ID 4 failed: new order request with DEX server 127.0.0.1:17273 market eth_btc failed: rpc error: error code 40: cannot use route 'limit' on an unauthorized connection - Order: 
```

2024-04-17 18:09 UTC, martonp reviewed
Seeing the same issue as @JoeGruffins

2024-04-21 09:37 UTC, ukane-philemon requested changes
utAck.

2024-04-21 09:37 UTC, ukane-philemon commented on client/core/bond.go
> +		}
Can remove the nested if: `if acctExists && dc.acct.locked() { return 0, newError(acctKeyErr, "acct locked %s (login first)", host) }`

2024-04-21 09:37 UTC, ukane-philemon commented on client/core/core.go
> +		return bond.Strength, bond.AssetID
Any reason why we insert instead of checking db? I assume the redeemed prepaid bond was added to the db, no?

2024-04-21 09:37 UTC, ukane-philemon commented on server/auth/registrar.go
> +		log.Warnf("Error sending prepaid bond result to user %v: %v", acctID, err)
This method is also used for normal bonds, no? can just say "bond result"

2024-04-23 18:47 UTC, martonp approved these changes

2024-04-24 07:24 UTC, JoeGruffins approved these changes

2024-04-30 03:25 UTC, merged