zec: Satisfy WalletHistorian.
decred/dcrdex pull request #2794
Opened 2024-05-30 08:29 UTC by JoeGruffins

2024-06-04 09:08 UTC, JoeGruffins commented
It looks like the harness loadbot is failing with `2024-06-04 18:07:27.051 [ERR] LOADBOT: exec error (zec) "./connect-alpha 41193": exit status 1: Error reading configuration file: Missing zcash.conf` I don't think related to these changes.

2024-06-15 14:21 UTC, buck54321 requested changes

2024-06-15 14:21 UTC, buck54321 commented on client/asset/zec/zec.go
> +		depositAddr, err := w.transparentAddress()
Can we use the `mnemonic_seedfp` parameter of the[ `getwalletinfo` result](https://zcash.github.io/rpc/getwalletinfo.html).

2024-06-17 08:47 UTC, JoeGruffins commented on client/asset/zec/transparent_rpc.go
> +}
Ok.

2024-06-17 08:50 UTC, JoeGruffins commented on client/asset/zec/zec.go
> +	// redeem transaction.
Changed to `defaultConfTarget`

2024-06-17 10:00 UTC, JoeGruffins commented
Using the encoded seed as the name and other things https://github.com/decred/dcrdex/compare/3c0fd17b16f9cc181b988ea018000502604bee05..352ba72b28a49c01524189d8ea68fa93bbe433af

loadbot is working for zec and zcl now, but zec fails rather quickly with:
```
2024-06-17 14:59:18.835 [DBG] CORE:STACKER:0[zec]: Attempting to fund Zcash order, maxFeeRate = 200, max swaps = 4
2024-06-17 14:59:18.842 [DBG] CORE:STACKER:0[zec]: Funding 0.04 BTC ZEC order with coins [50b3df8e186158f3377ec331b66fd4172ee504af6b9cd3bb54cecb66fef64f58:0] worth 1.2875 BTC
2024-06-17 14:59:18.847 [DBG] CORE:STACKER:0[zec]: Unlocked spent outpoint 50b3df8e186158f3377ec331b66fd4172ee504af6b9cd3bb54cecb66fef64f58:0
2024-06-17 14:59:18.850 [INF] LOADBOT[STACKER:0]: Balance: zec = 8739920000 available, 2703750000 locked
2024-06-17 14:59:18.850 [DBG] CORE:STACKER:0[zec]: returning coins [50b3df8e186158f3377ec331b66fd4172ee504af6b9cd3bb54cecb66fef64f58:0]
2024-06-17 14:59:18.851 [CRT] MANTLE:STACKER:0: Trade error (limit order, sell = true, qty = 4000000, rate = 83200000): new order request with DEX server 127.0.0.1:17273 market zec_btc failed: rpc error: error code 36: coin 50b3df8e186158f3377ec331b66fd4172ee504af6b9cd3bb54cecb66fef64f58:0 is locked
```

2024-06-17 10:00 UTC, JoeGruffins commented on client/asset/zec/zec.go
> +
Doing that.

2024-06-19 14:22 UTC, merged