mm/libxc: Coinbase
decred/dcrdex pull request #2809
Opened 2024-06-10 05:49 UTC by martonp

This will come on top of #2796 as that changes the CEX interface.

2025-03-22 15:25 UTC, buck54321 reviewed
Just a partial review to note some things that stick out. Looks like a handful of things might have changed or maybe the APIs have evolved a little.

2025-03-22 15:25 UTC, buck54321 commented on client/mm/libxc/coinbase.go
> +}
Slight refactor to improve flow and messaging.
```Go
func (c *cbWSConn) handleWebsocketMessage(b []byte) {
	var msg struct {
		Type        string `json:"type"`
		Message     string `json:"message"`
		Channel     string `json:"channel"`
		SequenceNum uint64 `json:"sequence_num"`
	}
	if err := json.Unmarshal(b, &msg); err != nil {
		c.log.Errorf("Error unmarshaling websocket message: %v", err)
		c.log.Errorf("Raw Message: %s", string(b))
	}
	if msg.Type == "error" {
		c.log.Errorf("Websocket error: %s", msg.Message)
		return
	}

	lastSeq := c.seq.Swap(msg.SequenceNum)
	if lastSeq != 0 && lastSeq != msg.SequenceNum-1 {
		c.log.Errorf("Websocket message out of sequence. %d -> %d", lastSeq, msg.SequenceNum)
		c.setSynced(false)

		// Will resubscribe in handleSubscriptionMessage.
		c.subUnsub(false)
		return
	}

	switch msg.Channel {
	case c.channelID:
		c.msgHandler(b)
	case "subscriptions":
		c.handleSubscriptionMessage(b)
	default:
		c.log.Errorf("Websocket message for unknown channel %q", msg.Channel)
	}
}
```

2025-03-22 15:25 UTC, buck54321 commented on client/mm/libxc/coinbase.go
> +	endpoint := fmt.Sprintf("v2/accounts/%s/transactions", acctID)
I see there are potentially newer api docs at https://docs.cdp.coinbase.com/exchange/reference/exchangerestapi_postwithdrawcrypto

2025-03-22 15:25 UTC, buck54321 commented on client/mm/libxc/coinbase.go
> +		if err := c.request(ctx, http.MethodGet, "api/v3/brokerage/accounts", v, nil, &res); err != nil {
Hmm. I also see docs at https://docs.cdp.coinbase.com/exchange/reference/exchangerestapi_getaccount that are a little different.

2025-03-25 13:53 UTC, martonp commented on client/mm/libxc/coinbase.go
> +// subscription to each market. cbWSConn subscribes to a single channel
Here is the recommendation: https://docs.cdp.coinbase.com/advanced-trade/docs/ws-setup-guide#best-practices-for-subscriptions

2025-03-25 14:11 UTC, martonp commented on client/mm/libxc/binance.go
> +
These must have been used in `binance.go` at some point, but then got removed.

2025-03-25 14:26 UTC, martonp commented on client/mm/libxc/coinbase.go
> +		if err := c.request(ctx, http.MethodGet, "api/v3/brokerage/accounts", v, nil, &res); err != nil {
You're looking at the Coinbase Exchange API, which is for institutions. We're using the Advanced Trade API, for individuals.

https://docs.cdp.coinbase.com/advanced-trade/reference/retailbrokerageapi_getaccounts

2025-03-25 14:28 UTC, martonp commented on client/mm/libxc/coinbase.go
> +	endpoint := fmt.Sprintf("v2/accounts/%s/transactions", acctID)
Same comment for this as below.. this is the Coinbase Exchange API, not the Advanced Trade API.

2025-03-26 07:54 UTC, JoeGruffins approved these changes
Unsure if I can test, but looks great!

2025-03-26 07:54 UTC, JoeGruffins commented on client/mm/libxc/coinbase.go
> +			fmt.Println("--reconnected")
Can use logger here?

2025-03-26 07:54 UTC, JoeGruffins commented on client/mm/libxc/coinbase.go
> +// in the past 3 days.
```suggestion
// ConfirmDeposit checks if a deposit has been confirmed and returns the
// amount deposited. This will only work for deposits that have been made
// in the past 3 days.
```

2025-04-02 04:08 UTC, buck54321 requested changes
I opened an ltc-usdc.polygon market on bison.exchange if anybody wants to test.

2025-04-02 04:08 UTC, buck54321 commented on client/mm/libxc/coinbase.go
> +	}
Got a bunch of these. They keep coming.
```
2025-04-02 03:59:00.200 [ERR] MM[AMM-bison.exchange:7232-2-966001]: Error canceling CEX trade 83b61061-de7d-4ca0-b0b6-e4c63302c85a: cancellation failed: UNKNOWN_CANCEL_ORDER
2025-04-02 03:59:00.200 [INF] MM[AMM-bison.exchange:7232-2-966001]: Cex trade 83b61061-de7d-4ca0-b0b6-e4c63302c85a was cancelled before it was filled
2025-04-02 03:59:15.216 [ERR] MM[AMM-bison.exchange:7232-2-966001]: Error canceling CEX trade 83b61061-de7d-4ca0-b0b6-e4c63302c85a: cancellation failed: UNKNOWN_CANCEL_ORDER
2025-04-02 03:59:15.216 [INF] MM[AMM-bison.exchange:7232-2-966001]: Cex trade 83b61061-de7d-4ca0-b0b6-e4c63302c85a was cancelled before it was filled
2025-04-02 03:59:30.202 [ERR] MM[AMM-bison.exchange:7232-2-966001]: Error canceling CEX trade 83b61061-de7d-4ca0-b0b6-e4c63302c85a: cancellation failed: UNKNOWN_CANCEL_ORDER
2025-04-02 03:59:30.202 [INF] MM[AMM-bison.exchange:7232-2-966001]: Cex trade 83b61061-de7d-4ca0-b0b6-e4c63302c85a was cancelled before it was filled
```

2025-04-02 04:08 UTC, buck54321 commented on client/mm/libxc/coinbase.go
> +	}
I'm actually seeing this for with a different trade ID for every match.

2025-04-03 18:50 UTC, martonp commented on client/mm/libxc/coinbase.go
> +			}
The issue was that the goroutine updating the balance used a timer instead of a ticker.

2025-04-03 18:51 UTC, martonp commented on client/mm/libxc/coinbase.go
> +	}
It's working for me now.. can you try again?

2025-04-12 15:31 UTC, buck54321 commented on client/comms/wsconn.go
> +		}
This is handled by our `SetPingHandler` function. It shouldn't be necessary anywhere else. What are you seeing?

2025-04-12 15:32 UTC, buck54321 commented on client/mm/exchange_adaptor.go
> +		effects.Locked[trade.BaseID] = utils.SafeSub(trade.Qty, trade.BaseFilled)
This requires comment too. We can't brush math inconsistencies under the rug.

2025-04-12 15:40 UTC, buck54321 commented on client/comms/wsconn.go
> +		}
I see your note about pings/heartbeats now. This solution is a little hacky, and doesn't really capture the intention of ping/pong or the heartbeat channel. Wouldn't it be better to reset the read deadline from **coinbase.go** when the heartbeat is received.

2025-04-12 16:47 UTC, buck54321 commented on client/mm/libxc/coinbase.go
> +	return nil
```Go
var errCode int
var errResp json.RawMessage
if err := dexnet.Do(req, &res, dexnet.WithStatusFunc(func(code int) { errCode = code }), dexnet.WithErrorParsing(&errResp)); err != nil {
	if errCode == http.StatusUnauthorized {
		return fmt.Errorf("authentication failure")
	}
	return fmt.Errorf("error response (%d): %s", errCode, string(errResp))
}
return nil
```

2025-04-12 16:47 UTC, buck54321 commented on client/mm/libxc/coinbase.go
> +func toAtomicFromString(v string, ui *dex.UnitInfo) uint64 {
Unused

2025-04-13 23:38 UTC, martonp commented on client/comms/wsconn.go
> +		}
Should `PingWait` just be renamed to `ReadWait`? Is there a reason to specifically wait for ping messages? The reason for pings is to confirm that the connection is alive, and if a non-ping message comes through, it confirms it as well.

2025-04-13 23:55 UTC, martonp commented on client/mm/exchange_adaptor.go
> +		effects.Locked[trade.BaseID] = utils.SafeSub(trade.Qty, trade.BaseFilled)
I've added a log. The underlying issue in the coinbase implementation was fixed.

2025-05-14 06:42 UTC, JoeGruffins approved these changes

2025-05-14 06:43 UTC, merged