fiatrates: translate name for weth for coinpaprika
decred/dcrdex pull request #2850
Opened 2024-06-29 18:04 UTC by buck54321

2024-07-01 01:54 UTC, ukane-philemon requested changes

2024-07-01 01:54 UTC, ukane-philemon commented on dex/fiatrates/fiatrates.go
>  	}
Also, set `symbol` to `weth`.

```suggestion
name = "weth"
symbol = "weth"
}
```

2024-07-01 09:04 UTC, martonp approved these changes

2024-07-01 09:04 UTC, martonp commented on dex/fiatrates/fiatrates.go
>  	}
`symbol` is already "weth".

2024-07-03 03:50 UTC, JoeGruffins approved these changes

2024-07-03 04:06 UTC, ukane-philemon approved these changes

2024-07-03 04:06 UTC, ukane-philemon commented on dex/fiatrates/fiatrates.go
>  	}
Oh yeah. Had a glance.

2024-07-08 14:21 UTC, merged