mm: Close book feeds
decred/dcrdex pull request #2907
Opened 2024-08-11 06:26 UTC by martonp

Book feeds were not being closed, leading to warning logs.

2024-08-11 10:22 UTC, peterzen commented
LGTM

2024-08-12 15:38 UTC, buck54321 requested changes

2024-08-12 15:38 UTC, buck54321 commented on client/mm/mm_simple_arb.go
> +				bookFeed.Close()
Put it up after `defer wg.Done()` please. Here and two other places.

2024-08-12 15:38 UTC, buck54321 commented on client/mm/mm_simple_arb.go
> +				bookFeed.Close()
Looks like you need to close this if you get an error from `SubscribeMarket` above too.

2024-08-12 17:18 UTC, buck54321 approved these changes

2024-08-12 17:18 UTC, merged