app: Fix amounts displayed for token transactions in tx history
decred/dcrdex pull request #2998
Opened 2024-09-29 11:41 UTC by martonp

When displaying token transactions on the wallet page for the parent asset, the unit info for the parent asset was being used, causing incorrect amounts.

2024-09-30 09:03 UTC, JoeGruffins approved these changes

2024-09-30 14:12 UTC, dev-warrior777 approved these changes
Looks good. The linting issues are fixed in #2996

2024-10-06 16:11 UTC, buck54321 requested changes

2024-10-07 08:08 UTC, martonp commented on client/webserver/site/src/js/wallets.ts
> +      amtAssetID = tx.tokenID
Not necessarily. The token transactions show up in the transaction history of both the parent asset and the token asset.

2024-10-07 08:10 UTC, martonp commented on client/webserver/site/src/js/wallets.ts
> +      if (assetID !== tx.tokenID) feesAssetID = assetID
Same answer as above.

2024-10-11 00:31 UTC, buck54321 approved these changes

2024-10-11 00:31 UTC, merged