client/asset/btc: sendrawtransaction syntax change
decred/dcrdex pull request #633
Opened 2020-08-24 22:18 UTC by chappjc

From node version 0.19, the `sendrawtransaction` RPC changed the
`allowHighFees` boolean argument to a `maxFeeRate` numeric argument.
btcd's rpclient detects which to use depending on the version obtained
from `getnetworkinfo`, however this detection is broken for nodes that
report a subversion that is not of the form "/Satoshi:0.20.1/". For
example, rpcclient fails to recognize "/LitecoinCore:0.20.1/" as
requiring the boolean argument.

To fix this, implement `sendrawtransaction` with `rawrequest`.
The `(*ExchangeWallet).SendRawTransaction` method will use the correct
argument type according to the integer network version (e.g. 200100)
detected on `ExchangeWallet` construction.

2020-08-31 08:14 UTC, JoeGruffins approved these changes

2020-08-31 08:14 UTC, JoeGruffins commented on client/asset/btc/btc.go
> +		return json.Unmarshal(b, thing)
newline in odd place

2020-08-31 08:14 UTC, JoeGruffins commented on client/asset/btc/btc.go
> +			fmt.Println(string(p))
Is this print meant to be here?

2020-09-18 14:12 UTC, buck54321 requested changes

2020-11-02 18:54 UTC, chappjc commented
Unless 0.18 doesn't work presently, and I think it does, I'm going to close this and we can revisit when/if 0.20 ever comes out.

2020-11-18 17:59 UTC, closed without merging