multi: add loglocal flag, default to utc
decred/dcrdex pull request #657
Opened 2020-09-02 03:19 UTC by chappjc

This adds a `--loglocal` switch to use the local time zone in log entries, with the default to log UTC time stamps.

This uses https://github.com/decred/slog/pull/5

2020-09-04 08:08 UTC, JoeGruffins approved these changes
Working well. 
My opinion: I would rather have local time the default to be honest. The flag could be --utc. This may have been discussed somewhere before.

2020-09-04 13:44 UTC, chappjc commented
I think most people would probably choose local time.  This is me considering the practical need to be able to make any sense of other people's logs.  I figure if someone really wants to be difficult with getting support, they can use local logs.

Still, I can imagine the reverse message like

```
2020-09-03 14:06:50.697 [INF] MAIN: Logging with Local time stamps. Current UTC time is 19:06:50.697
```

But there's next to no chance I'd ever see that to figure out the delta.

Another solution might be to completely modify the time format to include timezone offset, but that's another slog change, and a bigger one.

2020-09-06 01:19 UTC, JoeGruffins commented
I see, from a support standpoint it does make sense. This change is fine with me.

2020-09-07 20:04 UTC, buck54321 requested changes
Just the function signature thing, but can we also make local the default on the simnet dcrdex?

2020-09-08 14:44 UTC, chappjc commented
Always local for simnet now:

```
$    date
Tue Sep  8 09:41:23 AM CDT 2020

$    ./dexc --simnet
2020-09-08 09:41:39.697 [DBG] CORE: new client core created

$    ./dexc --testnet
2020-09-08 14:41:52.988 [INF] DEXC: Logging with UTC time stamps. Current local time is 09:41:52 CDT

$    ./dexc --testnet --loglocal
2020-09-08 09:42:00.760 [DBG] CORE: new client core created

```

2020-09-08 15:54 UTC, buck54321 commented on client/cmd/dexc/main.go
> +	}
Oh. I really just meant for the dcrdex simnet harness `dex/testing/dcrdex/harness.sh`, but this is fine too.

2020-09-08 15:54 UTC, buck54321 approved these changes

2020-09-10 19:22 UTC, merged