spec: define cancel ratio new user period
decred/dcrdex pull request #671
Opened 2020-09-08 15:36 UTC by chappjc

Define a new-user bring up / grace period with respect to the enforcement of cancellation ratio.  Implementation in https://github.com/decred/dcrdex/pull/638

2020-09-09 23:18 UTC, buck54321 requested changes

2020-09-09 23:18 UTC, buck54321 commented on spec/community.mediawiki
> +completed order count (i.e. canceled + fully settled), <code>total</code>,
~~(i.e. canceled + fully settled)~~ This was defined just a few lines up.

2020-09-09 23:18 UTC, buck54321 commented on spec/community.mediawiki
> +meeting the required cancellation rate threshold:
"meeting" is a bit ambiguous as to whether that would constitute a violation or not.

2020-09-17 02:24 UTC, JoeGruffins approved these changes
A few instances of cancellation ratio still, not sure if it matters too much:
```
$ grep -rn cancellation\ ratio
server/swap/swap.go:1173:                       // status, counted against the user's cancellation ratio, and a
server/swap/swap.go:1206:                       // closes the account before the possibility of a cancellation ratio
server/market/market.go:1300:// "revoked", (3) inform the auth manager of the action for cancellation ratio
$ grep -rn cancellation_ratio
spec/fundamentals.mediawiki:99:| cancelmax      || float || the [[community.mediawiki/#Rule_3_An_accounts_cancellation_ratio_must_not_exceed_the_threshold|cancellation threshold]]
```

2020-09-19 22:38 UTC, buck54321 approved these changes

2020-09-21 13:41 UTC, merged