core,ui: add confirmation for currently waiting swap
decred/dcrdex pull request #805
Opened 2020-11-02 12:48 UTC by buck54321

Add confirmation count to match cards on the order details page, for matches in `MakerSwapCast` or `TakerSwapCast`. It's a bigger job than it sounds like, because 1) we weren't tracking confirmation count on our own swaps yet, and 2) I didn't think we should add the count unless it updated live, so the count, match status, and various coin ID links will update live now. 

<img src="https://user-images.githubusercontent.com/6109680/97868751-ddd0ea00-1cd5-11eb-9051-7b8e06033e9a.png" width="250">

There are just a few more pieces needed to make the whole page update live. Will save the rest for another PR.

2020-11-02 16:42 UTC, chappjc requested changes

2020-11-02 16:42 UTC, chappjc commented on client/core/notification.go
> +		OrderID:      oid[:],
This is fine, but you could do `OrderID:     t.ID().Bytes(),`

2020-11-02 16:42 UTC, chappjc commented on client/core/types.go
> +// matchFromMmatchFromMetaMatchWithConfs constructs a *Match from a *MetaMatch,
stray "m" in the function name in docs

2020-11-02 16:42 UTC, chappjc commented on client/core/types.go
> +// SwapCoin.
SwapCoin -> "swap Coin"?

2020-11-02 16:42 UTC, chappjc commented on client/core/types.go
> +	sell := ord.Trade().Sell
`ord.Trade()` is nil for cancel orders, and thus panic, and while this shouldn't be called for a cancel order match (I think) I'd feel better if this function had logic to deal with that possibility.

2020-11-02 16:42 UTC, chappjc commented on client/core/types.go
> +	FundingCoins []*Coin           `json:"fundingCoins"`
This and the the Match changes rule out 0.1.x unfortunately, which is no big deal as we'll move on to 0.2.0 right away.

2020-11-02 16:42 UTC, chappjc commented on client/core/trade.go
> +		} else {
No `else` needed since previous block ends with a `return`.  Same in `isRedeemable`.

2020-11-07 19:08 UTC, chappjc commented
Bump, but no rush.  Just wanted to make sure this PR doesn't get lost.

2020-11-08 00:01 UTC, buck54321 commented on client/core/notification.go
> +func (c *Core) updateCoreMatch(n *MatchNote) {
This function and the way it's called from the notification feed might be a model for a solution to https://github.com/decred/dcrdex/issues/379.

2020-11-09 17:23 UTC, chappjc approved these changes
Looks good.  Working flawlessly.

2020-11-09 17:27 UTC, merged