processAudit runs txn search async, redo match res. locking
decred/dcrdex pull request #819
Opened 2020-11-06 01:05 UTC by chappjc

2020-11-06 19:36 UTC, chappjc commented on client/core/trade.go
> +					t.dc.log.Infof("Still searching for contract coin %v (%s) for match %v. "+
Still considering if it should still try at least a couple times even if it is revoked, or is being revoked a good indicator that the audit now irrelevant...

2020-11-06 20:50 UTC, chappjc commented
Working as intended, although I'm uncertain about the audit timeout during resolution.

2020-11-10 19:31 UTC, chappjc commented on client/core/trade.go
> +	if needsResolution {
Now making sure match status and proof data updates happen before firing off the resolution goroutine.

2020-11-10 19:49 UTC, chappjc commented on client/core/trade.go
> +					t.dc.log.Infof("Still searching for contract coin %v (%s) for match %v. "+
Audit is only useful for the normal swap negotiation path, so I've concluded no, the audit is not needed for a revoked match, which will go to refund.  However, I believe there is an opportunity for an improvement that would require more work: https://github.com/decred/dcrdex/issues/829

2020-11-10 20:43 UTC, buck54321 requested changes
Tests well. 

I do feel like there is some new added complexity around lock handling in `status.go` that could have been avoided. For example, the new (exported?) getter methods in `trackedTrade` are only needed because we're not locking for all of `resolveConflictWithServerData` anymore. But there were only two paths (I think) that had the potential for long delays from mutex locking, and you've already stated that the correct solution is to run `auditContract` in a `goroutine` and unlock. New pattern seems racier.

2020-11-10 20:43 UTC, buck54321 commented on client/core/trade.go
> +// a long period, and should be run in a goroutine. The trackedTrade mtx must
> This may block for a long period

Well, it'll block for as long as `timeout`, which is not necessarily long.

2020-11-10 20:45 UTC, chappjc commented on client/core/trade.go
> +		err := t.auditContract(match, audit.CoinID, audit.Contract, 48*time.Hour)
it's broadcast timeout *after swapconf*, which is harder to discern.  This time might as well be 1 year as this just breaks on revoke.

2020-11-10 20:47 UTC, chappjc commented on client/core/trade.go
> +}
Just because of the locking.  Will unexport.

But I don't see a way to run auditContract in a goroutine in the resolvers.

2020-11-10 20:52 UTC, buck54321 commented on client/core/trade.go
> +}
In another goroutine?

2020-11-11 15:54 UTC, chappjc commented
I also snuck in a notification with the lats commit yesterday.  It's not pretty because the IDs are too long, but I think it needs at least the coin ID (utxo)

![image](https://user-images.githubusercontent.com/9373513/98833481-b4197080-2403-11eb-85bd-a2f8a53aecc0.png)

2020-11-11 17:06 UTC, chappjc commented
I discovered a very similar issue to the one addressed by this PR, which is the clients 'init' and 'redeem' requests are also blocking as they finalizeSwapAction and finalizeRedeemAction wait until the server responds.  A server response requires the server to search for the txn, so we have a similar failure mode as we saw with the audits.  We should address this without delay.

2020-11-11 17:10 UTC, chappjc commented on client/core/trade.go
> +			if err == nil {
@buck54321 The hack I was using to simulate slow wallet AuditContract discovery of the coin is the following right after `AuditContract`:

```go
if tries < 13 {
	err = asset.CoinNotFoundError
}
```

2020-11-11 20:29 UTC, chappjc commented
With that rebase, I added one commit (https://github.com/decred/dcrdex/pull/819/commits/703767f2f2882b8e9f3e5c751336434da770af83) that adapts the recheck interval to the recently raised default broadcast timeout so that periodic ticks are every 90 seconds instead of every 4 minutes (12 minutes / 3).
The commit also tweaks the `checkTrades` flow so that the `tradeMtx` is never locked while a `trackedTrade` is locked. We don't want the trade map held unnecessarily, especially given the possibility for a trade to remain locked for a significant duration (e.g. `finalizeSwapAction`).

2020-11-11 20:37 UTC, buck54321 approved these changes

2020-11-11 20:37 UTC, buck54321 commented on client/core/core_test.go
> +		fmt.Println(<-rig.db.updateMatchChan)
Did you mean to leave the `Println`?

2020-11-11 20:37 UTC, buck54321 commented on client/core/trade.go
> +				if tries > 0 && tries%12 == 0 {
Love the notification metering.

2020-11-11 21:27 UTC, merged